# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 660)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 660))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Pictures/Leaf_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTab.setEnabled(True)
        font = QtGui.QFont()
        self.mainTab.setFont(font)
        self.mainTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.mainTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mainTab.setElideMode(QtCore.Qt.ElideNone)
        self.mainTab.setDocumentMode(False)
        self.mainTab.setObjectName("mainTab")
        self.pretraitement = QtWidgets.QWidget()
        self.pretraitement.setObjectName("pretraitement")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pretraitement)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.image_btn = QtWidgets.QPushButton(self.pretraitement)
        self.image_btn.setMaximumSize(QtCore.QSize(16777215, 33))
        self.image_btn.setStyleSheet("font-size:15px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Pictures/Import_35px_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.image_btn.setIcon(icon1)
        self.image_btn.setIconSize(QtCore.QSize(20, 20))
        self.image_btn.setObjectName("image_btn")
        self.horizontalLayout_4.addWidget(self.image_btn)
        self.lineEditPath = QtWidgets.QLineEdit(self.pretraitement)
        self.lineEditPath.setEnabled(False)
        self.lineEditPath.setMaximumSize(QtCore.QSize(16777215, 33))
        self.lineEditPath.setStyleSheet("font-size:16px;")
        self.lineEditPath.setObjectName("lineEditPath")
        self.horizontalLayout_4.addWidget(self.lineEditPath)
        self.save_btn = QtWidgets.QPushButton(self.pretraitement)
        self.save_btn.setEnabled(False)
        self.save_btn.setMaximumSize(QtCore.QSize(16777215, 33))
        self.save_btn.setStyleSheet("font-size:15px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Pictures/Save_96px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon2)
        self.save_btn.setIconSize(QtCore.QSize(20, 20))
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_4.addWidget(self.save_btn)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(74, -1, 0, -1)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.labelOpr = QtWidgets.QLabel(self.pretraitement)
        self.labelOpr.setMaximumSize(QtCore.QSize(140, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.labelOpr.setFont(font)
        self.labelOpr.setStyleSheet("font-size:15px;")
        self.labelOpr.setText("")
        self.labelOpr.setObjectName("labelOpr")
        self.horizontalLayout_12.addWidget(self.labelOpr)
        self.progressBar = QtWidgets.QProgressBar(self.pretraitement)
        self.progressBar.setMaximumSize(QtCore.QSize(220, 16777215))
        self.progressBar.setStyleSheet("")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_12.addWidget(self.progressBar)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line = QtWidgets.QFrame(self.pretraitement)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_5.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_ = QtWidgets.QGroupBox(self.pretraitement)
        self.groupBox_.setStyleSheet("font-size:15px;\n"
"")
        self.groupBox_.setObjectName("groupBox_")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 8, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 15, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 6, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setContentsMargins(-1, 1, -1, 0)
        self.formLayout_7.setHorizontalSpacing(38)
        self.formLayout_7.setVerticalSpacing(11)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalSliderG = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSliderG.setEnabled(False)
        self.horizontalSliderG.setMaximumSize(QtCore.QSize(150, 35))
        self.horizontalSliderG.setWhatsThis("")
        self.horizontalSliderG.setMinimum(0)
        self.horizontalSliderG.setMaximum(3)
        self.horizontalSliderG.setSingleStep(1)
        self.horizontalSliderG.setPageStep(10)
        self.horizontalSliderG.setProperty("value", 0)
        self.horizontalSliderG.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderG.setObjectName("horizontalSliderG")
        self.horizontalLayout_6.addWidget(self.horizontalSliderG)
        self.formLayout_7.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalSliderM = QtWidgets.QSlider(self.groupBox_3)
        self.horizontalSliderM.setEnabled(False)
        self.horizontalSliderM.setMaximumSize(QtCore.QSize(150, 35))
        self.horizontalSliderM.setMinimum(0)
        self.horizontalSliderM.setMaximum(3)
        self.horizontalSliderM.setSingleStep(1)
        self.horizontalSliderM.setProperty("value", 0)
        self.horizontalSliderM.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderM.setObjectName("horizontalSliderM")
        self.horizontalLayout_7.addWidget(self.horizontalSliderM)
        self.formLayout_7.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.gridLayout_4.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 6, -1, -1)
        self.formLayout.setHorizontalSpacing(36)
        self.formLayout.setVerticalSpacing(11)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushBrotateLeft = QtWidgets.QPushButton(self.groupBox_3)
        self.pushBrotateLeft.setEnabled(False)
        self.pushBrotateLeft.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushBrotateLeft.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../Pictures/Rotate Left_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushBrotateLeft.setIcon(icon3)
        self.pushBrotateLeft.setIconSize(QtCore.QSize(17, 17))
        self.pushBrotateLeft.setObjectName("pushBrotateLeft")
        self.horizontalLayout_5.addWidget(self.pushBrotateLeft)
        self.pushBrotateRight = QtWidgets.QPushButton(self.groupBox_3)
        self.pushBrotateRight.setEnabled(False)
        self.pushBrotateRight.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushBrotateRight.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../Pictures/Rotate Right_30px.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushBrotateRight.setIcon(icon4)
        self.pushBrotateRight.setIconSize(QtCore.QSize(17, 17))
        self.pushBrotateRight.setObjectName("pushBrotateRight")
        self.horizontalLayout_5.addWidget(self.pushBrotateRight)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(16)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.spinBangle = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBangle.setEnabled(False)
        self.spinBangle.setMinimumSize(QtCore.QSize(55, 25))
        self.spinBangle.setMaximumSize(QtCore.QSize(55, 25))
        self.spinBangle.setWrapping(False)
        self.spinBangle.setMinimum(0)
        self.spinBangle.setMaximum(360)
        self.spinBangle.setObjectName("spinBangle")
        self.horizontalLayout_8.addWidget(self.spinBangle)
        self.pushBrotate = QtWidgets.QPushButton(self.groupBox_3)
        self.pushBrotate.setEnabled(False)
        self.pushBrotate.setMaximumSize(QtCore.QSize(16777215, 27))
        self.pushBrotate.setObjectName("pushBrotate")
        self.horizontalLayout_8.addWidget(self.pushBrotate)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.gridLayout_4.addLayout(self.formLayout, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.formLayout_2.setHorizontalSpacing(45)
        self.formLayout_2.setVerticalSpacing(11)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spinBsigmaX = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBsigmaX.setEnabled(False)
        self.spinBsigmaX.setMinimumSize(QtCore.QSize(0, 24))
        self.spinBsigmaX.setMaximumSize(QtCore.QSize(55, 25))
        self.spinBsigmaX.setMinimum(1)
        self.spinBsigmaX.setMaximum(3)
        self.spinBsigmaX.setObjectName("spinBsigmaX")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBsigmaX)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.spinBArretes = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBArretes.setEnabled(False)
        self.spinBArretes.setMaximumSize(QtCore.QSize(55, 25))
        self.spinBArretes.setMaximum(2000)
        self.spinBArretes.setObjectName("spinBArretes")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBArretes)
        self.gridLayout_6.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_6.addWidget(self.line_3, 1, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.formLayout_3.setHorizontalSpacing(27)
        self.formLayout_3.setVerticalSpacing(11)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.spinBapprox = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBapprox.setEnabled(False)
        self.spinBapprox.setMinimumSize(QtCore.QSize(60, 25))
        self.spinBapprox.setMaximumSize(QtCore.QSize(55, 25))
        self.spinBapprox.setMinimum(0)
        self.spinBapprox.setMaximum(9)
        self.spinBapprox.setProperty("value", 5)
        self.spinBapprox.setObjectName("spinBapprox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBapprox)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.nbPointsC = QtWidgets.QLineEdit(self.groupBox_4)
        self.nbPointsC.setEnabled(False)
        self.nbPointsC.setMaximumSize(QtCore.QSize(60, 25))
        self.nbPointsC.setObjectName("nbPointsC")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.nbPointsC)
        self.gridLayout_6.addLayout(self.formLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_)
        self.groupBoxAffichage = QtWidgets.QGroupBox(self.pretraitement)
        self.groupBoxAffichage.setStyleSheet("font-size:15px;")
        self.groupBoxAffichage.setObjectName("groupBoxAffichage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxAffichage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.layoutPlotContour = QtWidgets.QGridLayout()
        self.layoutPlotContour.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.layoutPlotContour.setObjectName("layoutPlotContour")
        self.gridLayout_3.addLayout(self.layoutPlotContour, 1, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(70, -1, 70, -1)
        self.horizontalLayout_2.setSpacing(200)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushBimageFS = QtWidgets.QPushButton(self.groupBoxAffichage)
        self.pushBimageFS.setEnabled(False)
        self.pushBimageFS.setMaximumSize(QtCore.QSize(250, 35))
        self.pushBimageFS.setObjectName("pushBimageFS")
        self.horizontalLayout_2.addWidget(self.pushBimageFS)
        self.pushBcontourFS = QtWidgets.QPushButton(self.groupBoxAffichage)
        self.pushBcontourFS.setEnabled(False)
        self.pushBcontourFS.setMaximumSize(QtCore.QSize(250, 35))
        self.pushBcontourFS.setObjectName("pushBcontourFS")
        self.horizontalLayout_2.addWidget(self.pushBcontourFS)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        self.line_4 = QtWidgets.QFrame(self.groupBoxAffichage)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 1, 1, 1, 1)
        self.groupBoxContour = QtWidgets.QGroupBox(self.groupBoxAffichage)
        self.groupBoxContour.setObjectName("groupBoxContour")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBoxContour)
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_9.setContentsMargins(50, -1, 1, -1)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioBcontourEx = QtWidgets.QRadioButton(self.groupBoxContour)
        self.radioBcontourEx.setEnabled(False)
        self.radioBcontourEx.setObjectName("radioBcontourEx")
        self.horizontalLayout_9.addWidget(self.radioBcontourEx)
        self.radioBcontourIn = QtWidgets.QRadioButton(self.groupBoxContour)
        self.radioBcontourIn.setEnabled(False)
        self.radioBcontourIn.setObjectName("radioBcontourIn")
        self.horizontalLayout_9.addWidget(self.radioBcontourIn)
        self.gridLayout_3.addWidget(self.groupBoxContour, 0, 2, 1, 1)
        self.groupBoxImage = QtWidgets.QGroupBox(self.groupBoxAffichage)
        self.groupBoxImage.setObjectName("groupBoxImage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxImage)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(20, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioBimgSource = QtWidgets.QRadioButton(self.groupBoxImage)
        self.radioBimgSource.setEnabled(False)
        self.radioBimgSource.setObjectName("radioBimgSource")
        self.horizontalLayout.addWidget(self.radioBimgSource)
        self.checkBshowApprox = QtWidgets.QRadioButton(self.groupBoxImage)
        self.checkBshowApprox.setEnabled(False)
        self.checkBshowApprox.setObjectName("checkBshowApprox")
        self.horizontalLayout.addWidget(self.checkBshowApprox)
        self.checkBshowPointsC = QtWidgets.QRadioButton(self.groupBoxImage)
        self.checkBshowPointsC.setEnabled(False)
        self.checkBshowPointsC.setObjectName("checkBshowPointsC")
        self.horizontalLayout.addWidget(self.checkBshowPointsC)
        self.gridLayout_3.addWidget(self.groupBoxImage, 0, 0, 1, 1)
        self.layoutPlotImage = QtWidgets.QGridLayout()
        self.layoutPlotImage.setObjectName("layoutPlotImage")
        self.gridLayout_3.addLayout(self.layoutPlotImage, 1, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBoxAffichage)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.mainTab.addTab(self.pretraitement, "")
        self.modelisation = QtWidgets.QWidget()
        self.modelisation.setObjectName("modelisation")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.modelisation)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.modelisationTab = QtWidgets.QTabWidget(self.modelisation)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.modelisationTab.setFont(font)
        self.modelisationTab.setStyleSheet("font-size:16px;")
        self.modelisationTab.setTabPosition(QtWidgets.QTabWidget.South)
        self.modelisationTab.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.modelisationTab.setElideMode(QtCore.Qt.ElideLeft)
        self.modelisationTab.setDocumentMode(False)
        self.modelisationTab.setObjectName("modelisationTab")
        self.forme = QtWidgets.QWidget()
        self.forme.setStyleSheet("")
        self.forme.setObjectName("forme")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.forme)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_13 = QtWidgets.QLabel(self.forme)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 0, 1, 1)
        self.groupBspline = QtWidgets.QGroupBox(self.forme)
        self.groupBspline.setTitle("")
        self.groupBspline.setObjectName("groupBspline")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBspline)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layoutBspline = QtWidgets.QGridLayout()
        self.layoutBspline.setObjectName("layoutBspline")
        self.horizontalLayout_3.addLayout(self.layoutBspline)
        self.layoutBspline2 = QtWidgets.QGridLayout()
        self.layoutBspline2.setObjectName("layoutBspline2")
        self.horizontalLayout_3.addLayout(self.layoutBspline2)
        self.gridLayout_7.addWidget(self.groupBspline, 1, 0, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setHorizontalSpacing(40)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_22 = QtWidgets.QLabel(self.forme)
        self.label_22.setObjectName("label_22")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.distR = QtWidgets.QLCDNumber(self.forme)
        self.distR.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.distR.setFont(font)
        self.distR.setAutoFillBackground(False)
        self.distR.setStyleSheet("background-color:black;")
        self.distR.setFrameShape(QtWidgets.QFrame.Box)
        self.distR.setLineWidth(1)
        self.distR.setMidLineWidth(0)
        self.distR.setObjectName("distR")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.distR)
        self.gridLayout_7.addLayout(self.formLayout_4, 2, 0, 1, 1)
        self.modelisationTab.addTab(self.forme, "")
        self.texture = QtWidgets.QWidget()
        self.texture.setObjectName("texture")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.texture)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_14 = QtWidgets.QLabel(self.texture)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 0, 0, 1, 1)
        self.labelModTexture = QtWidgets.QLabel(self.texture)
        self.labelModTexture.setStyleSheet("font-size:16px;font-weight:bold;")
        self.labelModTexture.setText("")
        self.labelModTexture.setObjectName("labelModTexture")
        self.gridLayout_11.addWidget(self.labelModTexture, 0, 1, 1, 1)
        self.groupBLBP = QtWidgets.QGroupBox(self.texture)
        self.groupBLBP.setTitle("")
        self.groupBLBP.setObjectName("groupBLBP")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.groupBLBP)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_3.setSpacing(16)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtWidgets.QLabel(self.groupBLBP)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.labelTexture = QtWidgets.QLabel(self.groupBLBP)
        self.labelTexture.setMinimumSize(QtCore.QSize(550, 410))
        self.labelTexture.setMaximumSize(QtCore.QSize(550, 410))
        self.labelTexture.setText("")
        self.labelTexture.setObjectName("labelTexture")
        self.verticalLayout_3.addWidget(self.labelTexture)
        self.checkBtexture = QtWidgets.QCheckBox(self.groupBLBP)
        self.checkBtexture.setEnabled(False)
        self.checkBtexture.setObjectName("checkBtexture")
        self.verticalLayout_3.addWidget(self.checkBtexture)
        self.horizontalLayout_13.addLayout(self.verticalLayout_3)
        self.layoutHistLBP = QtWidgets.QGridLayout()
        self.layoutHistLBP.setObjectName("layoutHistLBP")
        self.horizontalLayout_13.addLayout(self.layoutHistLBP)
        self.gridLayout_11.addWidget(self.groupBLBP, 1, 0, 1, 2)
        self.modelisationTab.addTab(self.texture, "")
        self.couleur = QtWidgets.QWidget()
        self.couleur.setObjectName("couleur")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.couleur)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_15 = QtWidgets.QLabel(self.couleur)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 0, 0, 1, 1)
        self.labelModCouleur = QtWidgets.QLabel(self.couleur)
        self.labelModCouleur.setStyleSheet("font-size:16px;font-weight:bold;")
        self.labelModCouleur.setText("")
        self.labelModCouleur.setObjectName("labelModCouleur")
        self.gridLayout_9.addWidget(self.labelModCouleur, 0, 1, 1, 1)
        self.groupBcouleur = QtWidgets.QGroupBox(self.couleur)
        self.groupBcouleur.setTitle("")
        self.groupBcouleur.setObjectName("groupBcouleur")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.groupBcouleur)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.groupBcouleur)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.labelCouleur = QtWidgets.QLabel(self.groupBcouleur)
        self.labelCouleur.setMinimumSize(QtCore.QSize(550, 410))
        self.labelCouleur.setMaximumSize(QtCore.QSize(550, 410))
        self.labelCouleur.setText("")
        self.labelCouleur.setObjectName("labelCouleur")
        self.verticalLayout_2.addWidget(self.labelCouleur)
        self.checkBcolor = QtWidgets.QCheckBox(self.groupBcouleur)
        self.checkBcolor.setEnabled(False)
        self.checkBcolor.setObjectName("checkBcolor")
        self.verticalLayout_2.addWidget(self.checkBcolor)
        self.horizontalLayout_14.addLayout(self.verticalLayout_2)
        self.layoutPlothistHLS = QtWidgets.QGridLayout()
        self.layoutPlothistHLS.setObjectName("layoutPlothistHLS")
        self.horizontalLayout_14.addLayout(self.layoutPlothistHLS)
        self.gridLayout_9.addWidget(self.groupBcouleur, 1, 0, 1, 2)
        self.modelisationTab.addTab(self.couleur, "")
        self.gridLayout_8.addWidget(self.modelisationTab, 0, 0, 1, 1)
        self.mainTab.addTab(self.modelisation, "")
        self.reconnaissance = QtWidgets.QWidget()
        self.reconnaissance.setObjectName("reconnaissance")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.reconnaissance)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setContentsMargins(-1, 5, -1, 6)
        self.formLayout_8.setHorizontalSpacing(37)
        self.formLayout_8.setObjectName("formLayout_8")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setHorizontalSpacing(20)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_18 = QtWidgets.QLabel(self.reconnaissance)
        self.label_18.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_18.setStyleSheet("font-size:14px;")
        self.label_18.setObjectName("label_18")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.radioBforme = QtWidgets.QRadioButton(self.reconnaissance)
        self.radioBforme.setEnabled(False)
        self.radioBforme.setStyleSheet("font-size:14px;")
        self.radioBforme.setObjectName("radioBforme")
        self.horizontalLayout_15.addWidget(self.radioBforme)
        self.radioBtexture = QtWidgets.QRadioButton(self.reconnaissance)
        self.radioBtexture.setEnabled(False)
        self.radioBtexture.setStyleSheet("font-size:14px;")
        self.radioBtexture.setObjectName("radioBtexture")
        self.horizontalLayout_15.addWidget(self.radioBtexture)
        self.radioBcouleur = QtWidgets.QRadioButton(self.reconnaissance)
        self.radioBcouleur.setEnabled(False)
        self.radioBcouleur.setStyleSheet("font-size:14px;")
        self.radioBcouleur.setObjectName("radioBcouleur")
        self.horizontalLayout_15.addWidget(self.radioBcouleur)
        self.radioBtous = QtWidgets.QRadioButton(self.reconnaissance)
        self.radioBtous.setEnabled(False)
        self.radioBtous.setStyleSheet("font-size:14px;")
        self.radioBtous.setObjectName("radioBtous")
        self.horizontalLayout_15.addWidget(self.radioBtous)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_6)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(25)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushBrechechre = QtWidgets.QPushButton(self.reconnaissance)
        self.pushBrechechre.setEnabled(False)
        self.pushBrechechre.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushBrechechre.setObjectName("pushBrechechre")
        self.horizontalLayout_17.addWidget(self.pushBrechechre)
        self.pushBvider = QtWidgets.QPushButton(self.reconnaissance)
        self.pushBvider.setMaximumSize(QtCore.QSize(110, 16777215))
        self.pushBvider.setObjectName("pushBvider")
        self.horizontalLayout_17.addWidget(self.pushBvider)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.gridLayout_10.addLayout(self.formLayout_8, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.reconnaissance)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelimg = QtWidgets.QLabel(self.groupBox)
        self.labelimg.setMinimumSize(QtCore.QSize(445, 340))
        self.labelimg.setMaximumSize(QtCore.QSize(445, 340))
        self.labelimg.setSizeIncrement(QtCore.QSize(0, 0))
        self.labelimg.setText("")
        self.labelimg.setObjectName("labelimg")
        self.verticalLayout_8.addWidget(self.labelimg)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setHorizontalSpacing(31)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lcdNumber.setStyleSheet("background-color:black;")
        self.lcdNumber.setObjectName("lcdNumber")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lcdNumber)
        self.verticalLayout_8.addLayout(self.formLayout_5)
        self.labelProgression = QtWidgets.QLabel(self.groupBox)
        self.labelProgression.setStyleSheet("font-size:16px;font-weight:bold;")
        self.labelProgression.setText("")
        self.labelProgression.setObjectName("labelProgression")
        self.verticalLayout_8.addWidget(self.labelProgression)
        self.gridLayout_12.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 372, 493))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.layoutImages1 = QtWidgets.QVBoxLayout()
        self.layoutImages1.setObjectName("layoutImages1")
        self.horizontalLayout_16.addLayout(self.layoutImages1)
        self.layoutImages3 = QtWidgets.QVBoxLayout()
        self.layoutImages3.setObjectName("layoutImages3")
        self.horizontalLayout_16.addLayout(self.layoutImages3)
        self.layoutImages4 = QtWidgets.QVBoxLayout()
        self.layoutImages4.setObjectName("layoutImages4")
        self.horizontalLayout_16.addLayout(self.layoutImages4)
        self.layoutImages5 = QtWidgets.QVBoxLayout()
        self.layoutImages5.setObjectName("layoutImages5")
        self.horizontalLayout_16.addLayout(self.layoutImages5)
        self.layoutImages6 = QtWidgets.QVBoxLayout()
        self.layoutImages6.setObjectName("layoutImages6")
        self.horizontalLayout_16.addLayout(self.layoutImages6)
        self.layoutImages7 = QtWidgets.QVBoxLayout()
        self.layoutImages7.setObjectName("layoutImages7")
        self.horizontalLayout_16.addLayout(self.layoutImages7)
        self.layoutImages2 = QtWidgets.QVBoxLayout()
        self.layoutImages2.setObjectName("layoutImages2")
        self.horizontalLayout_16.addLayout(self.layoutImages2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_12.addWidget(self.scrollArea, 0, 2, 1, 1)
        self.gridLayout_10.addWidget(self.groupBox, 1, 0, 1, 1)
        self.mainTab.addTab(self.reconnaissance, "")
        self.gridLayout.addWidget(self.mainTab, 0, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.menuFichier = QtWidgets.QMenu(self.menubar)
        self.menuFichier.setObjectName("menuFichier")
        self.menuClasses = QtWidgets.QMenu(self.menubar)
        self.menuClasses.setObjectName("menuClasses")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        self.menuA_propos = QtWidgets.QMenu(self.menubar)
        self.menuA_propos.setObjectName("menuA_propos")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOuvrir = QtWidgets.QAction(MainWindow)
        self.actionOuvrir.setObjectName("actionOuvrir")
        self.actionSauvegarder = QtWidgets.QAction(MainWindow)
        self.actionSauvegarder.setObjectName("actionSauvegarder")
        self.actionQuitter = QtWidgets.QAction(MainWindow)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuFichier.addAction(self.actionOuvrir)
        self.menuFichier.addAction(self.actionSauvegarder)
        self.menuFichier.addAction(self.actionQuitter)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuClasses.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())
        self.menubar.addAction(self.menuA_propos.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTab.setCurrentIndex(0)
        self.modelisationTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reconnaissance des formes"))
        self.image_btn.setText(_translate("MainWindow", "Importer"))
        self.save_btn.setText(_translate("MainWindow", "sauvegarder"))
        self.groupBox_.setTitle(_translate("MainWindow", "Traitement :"))
        self.label.setText(_translate("MainWindow", "Lissage :"))
        self.label_10.setText(_translate("MainWindow", "Gaussien"))
        self.horizontalSliderG.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">niveau du filtre gaussien</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Médien"))
        self.label_2.setText(_translate("MainWindow", "Rotation :"))
        self.label_7.setText(_translate("MainWindow", "Pivoter"))
        self.label_3.setText(_translate("MainWindow", "Angle "))
        self.pushBrotate.setText(_translate("MainWindow", "rotate"))
        self.label_4.setText(_translate("MainWindow", "Contour interne :"))
        self.label_6.setText(_translate("MainWindow", "Coefficient SigmaX"))
        self.label_5.setText(_translate("MainWindow", "Nombre d\'arrêtes"))
        self.label_8.setText(_translate("MainWindow", "Points de courbure :"))
        self.label_9.setText(_translate("MainWindow", "Approximation"))
        self.spinBapprox.setPrefix(_translate("MainWindow", "0.00"))
        self.label_12.setText(_translate("MainWindow", "Nombre de points"))
        self.groupBoxAffichage.setTitle(_translate("MainWindow", "Affichage :"))
        self.pushBimageFS.setText(_translate("MainWindow", "Afficher en taille plus grande"))
        self.pushBcontourFS.setText(_translate("MainWindow", "Afficher en taille plus grande"))
        self.radioBcontourEx.setText(_translate("MainWindow", "Contour externe"))
        self.radioBcontourIn.setText(_translate("MainWindow", "Contour interne"))
        self.radioBimgSource.setText(_translate("MainWindow", "Image source"))
        self.checkBshowApprox.setText(_translate("MainWindow", "Approximation polygonale"))
        self.checkBshowPointsC.setText(_translate("MainWindow", " Points de courbure"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.pretraitement), _translate("MainWindow", "Prétraitement"))
        self.label_13.setText(_translate("MainWindow", "Descripteur de forme :"))
        self.label_22.setText(_translate("MainWindow", "Distance Radiale:"))
        self.modelisationTab.setTabText(self.modelisationTab.indexOf(self.forme), _translate("MainWindow", "Forme"))
        self.label_14.setText(_translate("MainWindow", "Descripteur Texture :"))
        self.label_16.setText(_translate("MainWindow", "Image LBP :"))
        self.checkBtexture.setText(_translate("MainWindow", "Visualiser grille des secteurs"))
        self.modelisationTab.setTabText(self.modelisationTab.indexOf(self.texture), _translate("MainWindow", "Texture"))
        self.label_15.setText(_translate("MainWindow", "Descripteur de couleur :"))
        self.label_17.setText(_translate("MainWindow", "Image couleur :"))
        self.checkBcolor.setText(_translate("MainWindow", "Visualiser grille des secteurs"))
        self.modelisationTab.setTabText(self.modelisationTab.indexOf(self.couleur), _translate("MainWindow", "Couleur"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.modelisation), _translate("MainWindow", "Modélisation"))
        self.label_18.setText(_translate("MainWindow", "Rechercher par :"))
        self.radioBforme.setText(_translate("MainWindow", "Forme géometrique"))
        self.radioBtexture.setText(_translate("MainWindow", "Texture"))
        self.radioBcouleur.setText(_translate("MainWindow", "Couleur"))
        self.radioBtous.setText(_translate("MainWindow", "Tous"))
        self.pushBrechechre.setText(_translate("MainWindow", "Rechercher"))
        self.pushBvider.setText(_translate("MainWindow", "vider"))
        self.label_19.setText(_translate("MainWindow", "Taux de reconnaissance"))
        self.mainTab.setTabText(self.mainTab.indexOf(self.reconnaissance), _translate("MainWindow", "Reconnaissance"))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier"))
        self.menuClasses.setTitle(_translate("MainWindow", "Classes"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))
        self.menuA_propos.setTitle(_translate("MainWindow", "A propos"))
        self.actionOuvrir.setText(_translate("MainWindow", "Ouvrir"))
        self.actionSauvegarder.setText(_translate("MainWindow", "Sauvegarder"))
        self.actionQuitter.setText(_translate("MainWindow", "Quitter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

